name: Deploy FHIR App to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: write-all # Ensure enough permissions for GitHub Pages deployment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use a specific, stable Node.js version

      - name: Install dependencies
        run: |
          # Change to the fhir-app directory before installing dependencies
          cd fhir-app
          npm install

      - name: Build app
        run: |
          # Change to the fhir-app directory before building the app
          cd fhir-app
          npm run build

      - name: Prepare for deployment
        run: |
          # Create a temporary directory at the root of the repository to hold the build output
          mkdir build_output
          # Move the *contents* of fhir-app/dist into the new build_output directory.
          # 'shopt -s dotglob' ensures hidden files (like .nojekyll if Vite creates it) are also moved.
          shopt -s dotglob
          mv fhir-app/dist/* build_output/
          shopt -u dotglob # Turn off dotglob after moving
          echo "Contents of build_output directory after move:"
          ls -al build_output/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Now, publish_dir points to the 'build_output' directory at the root of the workspace.
          publish_dir: build_output
          # Uncomment the line below if you want your app to be served from a subdirectory
          # on GitHub Pages (e.g., https://username.github.io/repo/fhir-app/).
          # destination_dir: fhir-app
