name: Deploy FHIR App to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: write-all # Ensure enough permissions for GitHub Pages deployment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use a specific, stable Node.js version

      - name: Install dependencies
        run: |
          # Change to the fhir-app directory before installing dependencies
          cd fhir-app
          npm install

      - name: Build app
        run: |
          # Change to the fhir-app directory before building the app
          cd fhir-app
          npm run build

      - name: Flatten build output for GitHub Pages
        run: |
          # Create a new directory at the root of the repository for the final publishable content
          mkdir public_html
          echo "Created public_html directory."

          # Move index.html from its nested location to the root of public_html
          # This is crucial because GitHub Pages expects index.html at the root.
          mv fhir-app/dist/src/index.html public_html/index.html
          echo "Moved index.html to public_html/."

          # Move the assets directory to public_html
          mv fhir-app/dist/assets public_html/assets
          echo "Moved assets to public_html/."

          # Create a .nojekyll file in the public_html directory.
          # This tells GitHub Pages not to process the directory with Jekyll
          # and ensures there's a hidden file for the 'peaceiris' action's glob pattern.
          touch public_html/.nojekyll
          echo "Created .nojekyll in public_html/."

          echo "Contents of public_html directory after flattening:"
          ls -al public_html/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public_html
          # This line is critical for deploying to a subdirectory on GitHub Pages.
          # Ensure its indentation is exactly two spaces more than 'with:'.
          destination_dir: fhir-app
